name: 2. Training & Docker Build (Advance)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'workflow-ci/**'
      - '.github/workflows/2_training_docker_ci.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Setup Job & Checkout
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependencies 
    - name: Install dependencies
      run: pip install pandas scikit-learn mlflow dagshub boto3

    # 4. Set MLflow Tracking URI 
    - name: Set MLflow Tracking URI
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      run: |
        echo "Setting up URI..."
        export MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/eksperimen_MSML_hudan-maulana-v2.mlflow

    # 5. Run mlflow project 
    - name: Run mlflow project
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd workflow-ci/MLProject
        
        
        mlflow run . --env-manager=local \
          -P n_estimators=100 \
          -P max_depth=10 \
          --experiment-name="Eksperimen_CI_Automatic_Run"

    # 6. Log in to Docker Hub (Sesuai Screenshot)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "huudz"  # <--- GANTI USERNAME KAMU
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Build Docker Model (Sesuai Screenshot)
    - name: Build Docker Model
      run: |
        IMAGE_NAME="hudan123/clv-model-hudan:latest" # <--- GANTI USERNAME KAMU
        
        echo "Building Docker Image..."
        
        
        mlflow models build-docker \
          -m "workflow-ci/MLProject/model_output" \
          -n "$IMAGE_NAME" \
          --enable-mlserver

    # 8. Push Docker Image (Sesuai Screenshot)
    - name: Push Docker Image
      run: |
        IMAGE_NAME="hudan123/clv-model-hudan:latest" # <--- GANTI USERNAME KAMU
        docker push "$IMAGE_NAME"